insert into STOCK_PRICE(PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE)values(101,'sprite',700.25);
insert into STOCK_PRICE(PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE)values(102,'Milkbottle',950.25);
insert into STOCK_PRICE(PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE)values(103,'ribbon',40.85);
insert into STOCK_PRICE(PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE)values(104,'glass',71.50);